import React, { useEffect, useMemo, useState } from 'react';
import { ErrorBlock, LoadingBlock } from '../components/ui/StateBlock';
import { getRecommendations } from '../lib/api';

const cardStyle = {
  background: '#fff',
  border: '1px solid #edf2f7',
  borderRadius: 16,
  padding: 16
};

function normalizePriority(value) {
  return String(value || '').toLowerCase();
}

export default function RecommendationsPage() {
  const [items, setItems] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let active = true;

    async function load() {
      try {
        setIsLoading(true);
        setError('');
        const data = await getRecommendations();
        if (!active) return;
        setItems(data?.items || []);
      } catch (err) {
        if (!active) return;
        setError(err.message || 'Failed to load recommendations.');
      } finally {
        if (active) setIsLoading(false);
      }
    }

    load();

    return () => {
      active = false;
    };
  }, []);

  const counters = useMemo(() => {
    return items.reduce(
      (acc, item) => {
        const priority = normalizePriority(item.priority);
        if (priority === 'high') acc.high += 1;
        if (priority === 'medium') acc.medium += 1;
        if (priority === 'low') acc.low += 1;
        return acc;
      },
      { high: 0, medium: 0, low: 0 }
    );
  }, [items]);

  return (
    <div style={{ padding: 24, display: 'grid', gap: 14 }}>
      <div>
        <h1 style={{ fontSize: 24, margin: 0 }}>Smart Recommendations</h1>
        <p style={{ color: '#6b7280', marginTop: 8, fontSize: 13 }}>Actionable suggestions generated by AI recommendation service.</p>
      </div>

      {error && <ErrorBlock message={error} />}

      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 12 }}>
        <div style={{ display: 'grid', gap: 10 }}>
          {isLoading && <LoadingBlock height={250} />}
          {!isLoading &&
            items.map((rec, index) => {
              const priority = normalizePriority(rec.priority);

              return (
                <div key={`${rec.type}-${rec.sku}-${index}`} style={cardStyle}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                    <span style={{ fontSize: 11, color: '#1d4ed8', background: '#eff6ff', borderRadius: 99, padding: '3px 8px', fontWeight: 700, textTransform: 'uppercase' }}>
                      {rec.type}
                    </span>
                    <span style={{ fontSize: 11, color: priority === 'high' ? '#dc2626' : '#d97706', fontWeight: 700, textTransform: 'uppercase' }}>{priority || 'unknown'}</span>
                  </div>
                  <div style={{ fontSize: 15, fontWeight: 650, marginBottom: 6 }}>{rec.action}</div>
                  <div style={{ fontSize: 12, color: '#6b7280', marginBottom: 5 }}>SKU: {rec.sku || 'N/A'}</div>
                  <div style={{ fontSize: 13, color: '#4b5563' }}>{rec.reason}</div>
                </div>
              );
            })}
        </div>

        <div style={{ background: 'linear-gradient(135deg,#1d4ed8,#4338ca)', color: '#fff', borderRadius: 16, padding: 16 }}>
          <div style={{ fontSize: 15, fontWeight: 700, marginBottom: 8 }}>AI Summary</div>
          {isLoading ? (
            <LoadingBlock height={120} />
          ) : (
            <>
              <p style={{ fontSize: 13, lineHeight: 1.6, opacity: 0.95 }}>
                Prioritize high-priority restock actions first, then execute medium-priority discount actions to optimize turnover.
              </p>
              <div style={{ marginTop: 10, fontSize: 12, opacity: 0.92 }}>High: {counters.high}</div>
              <div style={{ marginTop: 4, fontSize: 12, opacity: 0.92 }}>Medium: {counters.medium}</div>
              <div style={{ marginTop: 4, fontSize: 12, opacity: 0.92 }}>Low: {counters.low}</div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
